const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348117295067";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_13_47_07_03_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTUyLFxuICAgICAgICAzMyxcbiAgICAgICAgNjcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTgxLFxuICAgICAgICAzMSxcbiAgICAgICAgMjMsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA1NCxcbiAgICAgICAgMTA3LFxuICAgICAgICA5LFxuICAgICAgICAxMDYsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTUwLFxuICAgICAgICA4MixcbiAgICAgICAgMzQsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMjAwLFxuICAgICAgICA5MCxcbiAgICAgICAgOTQsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMDcsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxMTMsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjIxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDUzLFxuICAgICAgICAzMyxcbiAgICAgICAgMTczLFxuICAgICAgICAxOTYsXG4gICAgICAgIDc3LFxuICAgICAgICA3LFxuICAgICAgICA0MyxcbiAgICAgICAgMTcyLFxuICAgICAgICAxOTgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNjcsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTYzLFxuICAgICAgICA3LFxuICAgICAgICAxMixcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMDEsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNjksXG4gICAgICAgIDEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTc3LFxuICAgICAgICA1NCxcbiAgICAgICAgMjUxLFxuICAgICAgICA0NixcbiAgICAgICAgNDcsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTc2LFxuICAgICAgICAyNDQsXG4gICAgICAgIDYwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4LFxuICAgICAgICAxOTYsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjMzLFxuICAgICAgICA5MSxcbiAgICAgICAgMTAxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDExMixcbiAgICAgICAgMTA4LFxuICAgICAgICAyMjgsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxNDIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgNDMsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTk5LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTk3LFxuICAgICAgICA3MixcbiAgICAgICAgOTcsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjE1LFxuICAgICAgICAwLFxuICAgICAgICAxMjYsXG4gICAgICAgIDUwLFxuICAgICAgICAxODMsXG4gICAgICAgIDk4LFxuICAgICAgICAxNTIsXG4gICAgICAgIDEwNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjYsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTYxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTU1LFxuICAgICAgICA2OSxcbiAgICAgICAgMTA0LFxuICAgICAgICA3NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDgsXG4gICAgICAgIDgzLFxuICAgICAgICAxMjYsXG4gICAgICAgIDI1LFxuICAgICAgICAyMDksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMDUsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTM1LFxuICAgICAgICA5MCxcbiAgICAgICAgNDAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTEwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTMzLFxuICAgICAgICAxMzUsXG4gICAgICAgIDk0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzIsXG4gICAgICAgIDEwMixcbiAgICAgICAgNTgsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxOTksXG4gICAgICAgIDczLFxuICAgICAgICAxMzYsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMTAsXG4gICAgICAgIDE1OCxcbiAgICAgICAgNTcsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxMjYsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTkzLFxuICAgICAgICAxMzAsXG4gICAgICAgIDU4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDY3LFxuICAgICAgICA5MyxcbiAgICAgICAgOTAsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxMDQsXG4gICAgICAgIDE3NSxcbiAgICAgICAgOTZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTIsXG4gICAgICAgIDk1LFxuICAgICAgICA2NCxcbiAgICAgICAgMTk0LFxuICAgICAgICA1LFxuICAgICAgICAyMyxcbiAgICAgICAgNDEsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjQ0LFxuICAgICAgICA5NSxcbiAgICAgICAgNDQsXG4gICAgICAgIDk2LFxuICAgICAgICAxMzMsXG4gICAgICAgIDE5NixcbiAgICAgICAgOTEsXG4gICAgICAgIDM3LFxuICAgICAgICAyNDYsXG4gICAgICAgIDksXG4gICAgICAgIDE5NixcbiAgICAgICAgNTIsXG4gICAgICAgIDE4NyxcbiAgICAgICAgODMsXG4gICAgICAgIDE0MixcbiAgICAgICAgNDAsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjQwLFxuICAgICAgICA3OSxcbiAgICAgICAgMTQ0LFxuICAgICAgICA2MlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDEwOVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDQwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjUzLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjU1LFxuICAgICAgICAyMTQsXG4gICAgICAgIDc0LFxuICAgICAgICA3OSxcbiAgICAgICAgNTEsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNTksXG4gICAgICAgIDEyNSxcbiAgICAgICAgNjIsXG4gICAgICAgIDIwNCxcbiAgICAgICAgOTMsXG4gICAgICAgIDEzMixcbiAgICAgICAgODksXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTM1LFxuICAgICAgICA4NCxcbiAgICAgICAgMjA4LFxuICAgICAgICA5MyxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMTksXG4gICAgICAgIDM2LFxuICAgICAgICAyNCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxODQsXG4gICAgICAgIDE0NSxcbiAgICAgICAgNSxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMSxcbiAgICAgICAgOTEsXG4gICAgICAgIDI3LFxuICAgICAgICA1LFxuICAgICAgICAxODYsXG4gICAgICAgIDE2NSxcbiAgICAgICAgNDMsXG4gICAgICAgIDc5LFxuICAgICAgICA4MSxcbiAgICAgICAgMjQyLFxuICAgICAgICAxODQsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjA0LFxuICAgICAgICA4NyxcbiAgICAgICAgNTYsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxOSxcbiAgICAgICAgMTYyLFxuICAgICAgICA4MixcbiAgICAgICAgMTE3LFxuICAgICAgICAxNDIsXG4gICAgICAgIDIxNixcbiAgICAgICAgOTQsXG4gICAgICAgIDIwOSxcbiAgICAgICAgNTgsXG4gICAgICAgIDc4LFxuICAgICAgICAyMzYsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjUxLFxuICAgICAgICA1NyxcbiAgICAgICAgNjgsXG4gICAgICAgIDEzN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTcsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiRmdjUU5GZWFyRnFUdEMraVRLNzh6aHZlUTl2bWJhTmFQZUFwSExPMjdKMD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTE3Mjk1MDY3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI3QkY4NEQ3MTQ2MDI4REI3RUU4OTg2OUQyRTBBRTNEOVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMTQ0MzJcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTE3Mjk1MDY3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI0NTlFRTk3NUU5NjY2RUUwODM4MTQ1RDRDMjJENkQxNlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMTQ0MzNcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTE3Mjk1MDY3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIxNjlFOEU5NTMzMjRFQUNEQUE3QjNBNUMzNTUyODA5N1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMTQ0MzZcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTE3Mjk1MDY3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI1MUI1NzYyRURDOTA3NDU0OUM4MTU2RTgxRkY5N0M4OVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMTQ0MzdcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwidEZNQXNNeHhROXE2b1RwSUE0cFJPQVwiLFxuICBcInBob25lSWRcIjogXCJhZDYyNGZkZi00MmUwLTQwZWItODM0NC0xOTIwOTZiNDRhMmVcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjExLFxuICAgICAgMTY4LFxuICAgICAgMTU4LFxuICAgICAgMjM0LFxuICAgICAgMTEzLFxuICAgICAgMTY2LFxuICAgICAgNTEsXG4gICAgICAwLFxuICAgICAgNDMsXG4gICAgICAyMzksXG4gICAgICAxMDgsXG4gICAgICAzMixcbiAgICAgIDM2LFxuICAgICAgMTEwLFxuICAgICAgMTMsXG4gICAgICA4NyxcbiAgICAgIDg0LFxuICAgICAgMTM2LFxuICAgICAgNjksXG4gICAgICA2MlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMSxcbiAgICAgIDc4LFxuICAgICAgMjQwLFxuICAgICAgMzUsXG4gICAgICA1NyxcbiAgICAgIDE3MCxcbiAgICAgIDIxNixcbiAgICAgIDI1NSxcbiAgICAgIDQwLFxuICAgICAgMTE4LFxuICAgICAgOTAsXG4gICAgICA3OSxcbiAgICAgIDEyNyxcbiAgICAgIDE4LFxuICAgICAgMTcsXG4gICAgICAxMzMsXG4gICAgICAxNixcbiAgICAgIDIwOCxcbiAgICAgIDAsXG4gICAgICA3NlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCI0Vlc2NzZEOFwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0ODExNzI5NTA2NzoxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxMDc5ODQ1ODc4NjYzNTI6MUBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJHQkFERUJPXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTmlUZzhNR0VOdXNsYlFHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJoYkRqQ1hFRlhDSEdrMmFCRm5FRzRvZ3JUMjZ0Qlo5MlZxV0kvQTB1aVd3PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIkpsZVFLa2ZnMHUvSlF5R1dDcHBZRmR2Ym9YY2tYODIvZGRuakhvNFJNd0V3ckpHVFFmN25UVFdrYm5YTDJVeWhhdkYzMGx3Q1FIdUhTdlJSb3ZnMERRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlpNUjJITUFmMzltYU5ydFM5KzMyZGJ1MEJIcnVBcVpHY2JnZWlwdzhGNU1tZnArR0JBY0c0dEhvZWUzbHN0QzV2MzRydUFrT3RJK3RMUURhQloxMGlnPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDgxMTcyOTUwNjc6MUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDUsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDEwOFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwMDE0NDMxLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBS2pSXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLalIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ4ZEx3OHVqTWVZdGFVYzNFc3piYzArb3RoKzlCOEFjVUg1Z1FDT0prZ2YwPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE3NTExNzM1OTIsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMDAxNDQzMjAxNFwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
